{
	"version": 1643662551,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/hand-sheet0.png",
		"images/hand2-sheet0.png",
		"images/hand2-sheet1.png",
		"images/bloodax-sheet0.png",
		"images/bloodtable-sheet0.png",
		"images/bloodtable-sheet1.png",
		"images/bloodtable-sheet2.png",
		"images/bloodverticaltable-sheet0.png",
		"images/bloodverticaltable-sheet1.png",
		"images/bloodmenu-sheet0.png",
		"images/nonet-sheet0.png",
		"images/backg-sheet0.png",
		"images/table-sheet0.png",
		"images/ax-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/flash-sheet0.png",
		"images/shadowaxe-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite-sheet1.png",
		"images/ax2-sheet0.png",
		"images/showturn-sheet0.png",
		"images/cutscene-sheet0.png",
		"images/showwinlose-sheet0.png",
		"images/showwinlose-sheet1.png",
		"images/buttons-sheet0.png",
		"images/buttons-sheet1.png",
		"images/tv-sheet0.png",
		"images/backmony-sheet0.png",
		"images/backmony-sheet1.png",
		"images/backmony-sheet2.png",
		"images/ax3-sheet0.png",
		"images/ax4-sheet0.png",
		"images/menuback-sheet0.png",
		"images/flashm-sheet0.png",
		"images/flashm-sheet1.png",
		"images/sprite3-sheet0.png",
		"images/sprite3-sheet1.png",
		"images/menubutton-sheet0.png",
		"images/particles.png",
		"images/particles2.png",
		"images/menubutton2-sheet0.png",
		"images/particles3.png",
		"images/usertext.png",
		"images/spritefont.png",
		"images/howtplayimg-sheet0.png",
		"images/howtpitext-sheet0.png",
		"images/howtpitext-sheet1.png",
		"images/howtpitext-sheet2.png",
		"images/img-sheet0.png",
		"images/howtpibacktext-sheet0.png",
		"images/btnlayergame-sheet0.png",
		"images/btnlayergame-sheet1.png",
		"images/btnlayergame-sheet2.png",
		"images/backlayergame-sheet0.png",
		"images/rotatekadr-sheet0.png",
		"images/face-sheet0.png",
		"images/btnonline-sheet0.png",
		"images/btnonline-sheet1.png",
		"images/btnonline-sheet2.png",
		"images/face4-sheet0.png",
		"images/face4-sheet1.png",
		"images/k-sheet0.png",
		"images/k-sheet1.png",
		"images/search-sheet0.png",
		"images/search-sheet1.png",
		"images/search-sheet2.png",
		"images/freerotate-sheet0.png",
		"images/light-sheet0.png",
		"images/bar-sheet0.png",
		"media/scream1.ogg",
		"media/scream2.ogg",
		"media/scream3.ogg",
		"media/scream4.ogg",
		"media/scream5.ogg",
		"media/lose.ogg",
		"media/win.ogg",
		"media/axe.ogg",
		"media/axeperf cut.ogg",
		"media/axeperf.ogg",
		"media/buzz fade out.ogg",
		"media/seda takhte .ogg",
		"media/somareshmakoos.ogg",
		"media/click.ogg",
		"media/click1.ogg",
		"media/cry1.ogg",
		"media/cry2.ogg",
		"media/cry3.ogg",
		"media/room1.ogg",
		"media/room2.ogg",
		"media/room3.ogg",
		"media/room4.ogg",
		"media/other screams1.ogg",
		"media/other screams2.ogg",
		"media/other screams3.ogg",
		"media/room03.ogg",
		"media/qalb.ogg",
		"media/sa-at.ogg",
		"media/can you hear me now.ogg",
		"media/demon_girls.ogg",
		"media/no_don_t_touch_that.ogg",
		"media/dokme start.ogg",
		"media/game play1.ogg",
		"media/game play2.ogg",
		"media/game play3.ogg",
		"media/game play4.ogg",
		"media/rain1.ogg",
		"media/menu2.ogg",
		"media/s3.ogg",
		"media/s2.ogg",
		"media/s1.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}